var   PHOTOS = []
	, ASPECT_RATIO = 1.5
	, MAX_WIDTH = 175
	, MIN_WIDTH = 125
	, FLIPBOARD_SELECTOR = '.flipboard'
	, CARD_TEMPLATE = '#card-template'
	, CARD_SELECTOR = 'li'
	;

function flipboard () {
	var   $board = $(FLIPBOARD_SELECTOR)
		, $parent = $(window)
		, cards = []
		, card_template = _.template($(CARD_TEMPLATE).html())
		, shuffled_photos = []
		, columns, rows, width, height;
	
	
	function reset_dimensions () {
		var   full_width = $parent.width()
			, full_height = $parent.height()
			, raw_rows;
		
		// start with _ideal_ number of cols
		columns = Math.floor(full_width / MAX_WIDTH)
		
		do {

			width = Math.floor(full_width / columns);
			raw_rows = full_height / (width / ASPECT_RATIO);
			rows = Math.ceil(raw_rows);

		} while ( 

			// try increasing the number of columns and iterating if the height clipping is beyond a certain percentage
			rows - raw_rows >= 0.5 &&
			columns++ &&
			full_width/columns >= MIN_WIDTH
		);

		// now that we have the number of cols and rows, we compute the _ideal_ height
		height = Math.floor(full_height / rows);


		// at this point we have whole number for cols, rows and each card's dimensions
		// however, there will most likely be a few extra horizontal & vertical pixels
		// <del>so we first look for flexbox and outsource this problem to the browser if possible</del>
		// <ins>for now we'll just reduce the size of our board to suit our whole numbers</ins>

		$board.css({
			  'width': (columns * width) + 'px'
			, 'height': (rows * height) + 'px'
			, 'left': '50%'
			, 'top': '50%'
			, 'margin-left': - (columns * width / 2) + 'px'
			, 'margin-top': - (rows * height / 2) + 'px'
		})
	}
	
	function reset_cards () {
		var $card;
		
		// add new cards
		while (cards.length < columns * rows) {
			$card = $(card_template({
				  active: get_random_photo()
				, hidden: get_random_photo()
			}))
			
			$board.append($card);
			cards[cards.length] = $card[0];
		}
		
		// discard unused cards
		while (cards.length > columns * rows) $(cards.pop()).remove();
		
		// update card dimensions
		$(cards).width(width).height(height);
	}
	
	function get_random_photo () {
		if (!shuffled_photos.length) shuffled_photos = _.shuffle(PHOTOS);
		
		return shuffled_photos.shift();
	}
	
	reset_dimensions();
	reset_cards();
	
	$(window).resize(function() {
		reset_dimensions();
		reset_cards();
	});
}

function main () {
	flipboard();
}

PHOTOS = [
'media/DroidconIN (1).jpg',
'media/DroidconIN (2).jpg',
'media/DroidconIN (3).jpg',
'media/DroidconIN (4).jpg',
'media/DroidconIN (5).jpg',
'media/DroidconIN (6).jpg',
'media/DroidconIN (7).jpg',
'media/DroidconIN (8).jpg',
'media/DroidconIN (9).jpg',
'media/DroidconIN (10).jpg',
'media/DroidconIN (11).jpg',
'media/DroidconIN (12).jpg',
'media/DroidconIN (13).jpg',
'media/DroidconIN (14).jpg',
'media/DroidconIN (15).jpg',
'media/DroidconIN (16).jpg',
'media/DroidconIN (17).jpg',
'media/DroidconIN (18).jpg',
'media/DroidconIN (19).jpg',
'media/DroidconIN (20).jpg',
'media/DroidconIN (21).jpg',
'media/DroidconIN (22).jpg',
'media/DroidconIN (23).jpg',
'media/DroidconIN (24).jpg',
'media/DroidconIN (25).jpg',
'media/DroidconIN (26).jpg',
'media/DroidconIN (27).jpg',
'media/DroidconIN (28).jpg',
'media/DroidconIN (29).jpg',
'media/DroidconIN (30).jpg',
'media/DroidconIN (31).jpg',
'media/DroidconIN (32).jpg',
'media/DroidconIN (33).jpg',
'media/DroidconIN (34).jpg',
'media/DroidconIN (35).jpg',
'media/DroidconIN (36).jpg',
'media/DroidconIN (37).jpg',
'media/DroidconIN (38).jpg',
'media/DroidconIN (39).jpg',
'media/DroidconIN (40).jpg',
'media/DroidconIN (41).jpg',
'media/DroidconIN (42).jpg',
'media/DroidconIN (43).jpg',
'media/DroidconIN (44).jpg',
'media/DroidconIN (45).jpg',
'media/DroidconIN (46).jpg',
'media/DroidconIN (47).jpg',
'media/DroidconIN (48).jpg',
'media/DroidconIN (49).jpg',
'media/DroidconIN (50).jpg',
'media/DroidconIN (51).jpg',
'media/DroidconIN (52).jpg',
'media/DroidconIN (53).jpg',
'media/DroidconIN (54).jpg',
'media/DroidconIN (55).jpg',
'media/DroidconIN (56).jpg',
'media/DroidconIN (57).jpg',
'media/DroidconIN (58).jpg',
'media/DroidconIN (59).jpg',
'media/DroidconIN (60).jpg',
'media/DroidconIN (61).jpg',
'media/DroidconIN (62).jpg',
'media/DroidconIN (63).jpg',
'media/DroidconIN (64).jpg',
'media/DroidconIN (65).jpg',
'media/DroidconIN (66).jpg',
'media/DroidconIN (67).jpg',
'media/DroidconIN (68).jpg',
'media/DroidconIN (69).jpg',
'media/DroidconIN (70).jpg',
'media/DroidconIN (71).jpg',
'media/DroidconIN (72).jpg',
'media/DroidconIN (73).jpg',
'media/DroidconIN (74).jpg',
'media/DroidconIN (75).jpg',
'media/DroidconIN (76).jpg',
'media/DroidconIN (77).jpg',
'media/DroidconIN (78).jpg',
'media/DroidconIN (79).jpg',
'media/DroidconIN (80).jpg',
'media/DroidconIN (81).jpg',
'media/DroidconIN (82).jpg',
'media/DroidconIN (83).jpg',
'media/DroidconIN (84).jpg',
'media/DroidconIN (85).jpg',
'media/DroidconIN (86).jpg',
'media/DroidconIN (87).jpg',
'media/DroidconIN (88).jpg',
'media/DroidconIN (89).jpg',
'media/DroidconIN (90).jpg',
'media/DroidconIN (91).jpg',
'media/DroidconIN (92).jpg',
'media/DroidconIN (93).jpg',
'media/DroidconIN (94).jpg',
'media/DroidconIN (95).jpg',
'media/DroidconIN (96).jpg',
'media/DroidconIN (97).jpg',
'media/DroidconIN (98).jpg',
'media/DroidconIN (99).jpg',
'media/DroidconIN (100).jpg',
'media/DroidconIN (101).jpg',
'media/DroidconIN (102).jpg',
'media/DroidconIN (103).jpg',
'media/DroidconIN (104).jpg',
'media/DroidconIN (105).jpg',
'media/DroidconIN (106).jpg',
'media/DroidconIN (107).jpg',
'media/DroidconIN (108).jpg',
'media/DroidconIN (109).jpg',
'media/DroidconIN (110).jpg',
'media/DroidconIN (111).jpg',
'media/DroidconIN (112).jpg',
'media/DroidconIN (113).jpg',
'media/DroidconIN (114).jpg',
'media/DroidconIN (115).jpg',
'media/DroidconIN (116).jpg',
'media/DroidconIN (117).jpg',
'media/DroidconIN (118).jpg',
'media/DroidconIN (119).jpg',
'media/DroidconIN (120).jpg',
'media/DroidconIN (121).jpg',
'media/DroidconIN (122).jpg',
'media/DroidconIN (123).jpg',
'media/DroidconIN (124).jpg',
'media/DroidconIN (125).jpg',
'media/DroidconIN (126).jpg',
'media/DroidconIN (127).jpg',
'media/DroidconIN (128).jpg',
'media/DroidconIN (129).jpg',
'media/DroidconIN (130).jpg',
'media/DroidconIN (131).jpg',
'media/DroidconIN (132).jpg',
'media/DroidconIN (133).jpg',
'media/DroidconIN (134).jpg',
'media/DroidconIN (135).jpg',
'media/DroidconIN (136).jpg',
'media/DroidconIN (137).jpg',
'media/DroidconIN (138).jpg',
'media/DroidconIN (139).jpg',
'media/DroidconIN (140).jpg',
'media/DroidconIN (141).jpg',
'media/DroidconIN (142).jpg',
'media/DroidconIN (143).jpg',
'media/DroidconIN (144).jpg',
'media/DroidconIN (145).jpg',
'media/DroidconIN (146).jpg',
'media/DroidconIN (147).jpg',
'media/DroidconIN (148).jpg',
'media/DroidconIN (149).jpg',
'media/DroidconIN (150).jpg',
'media/DroidconIN (151).jpg',
'media/DroidconIN (152).jpg',
'media/DroidconIN (153).jpg',
'media/DroidconIN (154).jpg',
'media/DroidconIN (155).jpg',
'media/DroidconIN (156).jpg',
'media/DroidconIN (157).jpg',
'media/DroidconIN (158).jpg',
'media/DroidconIN (159).jpg',
'media/DroidconIN (160).jpg',
'media/DroidconIN (161).jpg',
'media/DroidconIN (162).jpg',
'media/DroidconIN (163).jpg',
'media/DroidconIN (164).jpg',
'media/DroidconIN (165).jpg',
'media/DroidconIN (166).jpg',
'media/DroidconIN (167).jpg',
'media/DroidconIN (168).jpg',
'media/DroidconIN (169).jpg',
'media/DroidconIN (170).jpg',
'media/DroidconIN (171).jpg',
'media/DroidconIN (172).jpg',
'media/DroidconIN (173).jpg',
'media/DroidconIN (174).jpg',
'media/DroidconIN (175).jpg',
'media/DroidconIN (176).jpg',
'media/DroidconIN (177).jpg',
'media/DroidconIN (178).jpg',
'media/DroidconIN (179).jpg',
'media/DroidconIN (180).jpg',
'media/DroidconIN (181).jpg',
'media/DroidconIN (182).jpg',
'media/DroidconIN (183).jpg',
'media/DroidconIN (184).jpg',
'media/DroidconIN (185).jpg',
'media/DroidconIN (186).jpg',
'media/DroidconIN (187).jpg',
'media/DroidconIN (188).jpg',
'media/DroidconIN (189).jpg',
'media/DroidconIN (190).jpg',
'media/DroidconIN (191).jpg',
'media/DroidconIN (192).jpg',
'media/DroidconIN (193).jpg',
'media/DroidconIN (194).jpg',
'media/DroidconIN (195).jpg',
'media/DroidconIN (196).jpg',
'media/DroidconIN (197).jpg',
'media/DroidconIN (198).jpg',
'media/DroidconIN (199).jpg',
'media/DroidconIN (200).jpg',
'media/DroidconIN (201).jpg',
'media/DroidconIN (202).jpg',
'media/DroidconIN (203).jpg',
'media/DroidconIN (204).jpg',
'media/DroidconIN (205).jpg',
'media/DroidconIN (206).jpg',
'media/DroidconIN (207).jpg',
'media/DroidconIN (208).jpg',
'media/DroidconIN (209).jpg',
'media/DroidconIN (210).jpg',
'media/DroidconIN (211).jpg',
'media/DroidconIN (212).jpg',
'media/DroidconIN (213).jpg',
'media/DroidconIN (214).jpg',
'media/DroidconIN (215).jpg',
'media/DroidconIN (216).jpg',
'media/DroidconIN (217).jpg',
'media/DroidconIN (218).jpg',
'media/DroidconIN (219).jpg',
'media/DroidconIN (220).jpg',
'media/DroidconIN (221).jpg',
'media/DroidconIN (222).jpg',
'media/DroidconIN (223).jpg',
'media/DroidconIN (224).jpg',
'media/DroidconIN (225).jpg',
'media/DroidconIN (226).jpg',
'media/DroidconIN (227).jpg',
'media/DroidconIN (228).jpg',
'media/DroidconIN (229).jpg',
'media/DroidconIN (230).jpg',
'media/DroidconIN (231).jpg',
'media/DroidconIN (232).jpg',
'media/DroidconIN (233).jpg',
'media/DroidconIN (234).jpg',
'media/DroidconIN (235).jpg',
'media/DroidconIN (236).jpg',
'media/DroidconIN (237).jpg',
'media/DroidconIN (238).jpg',
'media/DroidconIN (239).jpg',
'media/DroidconIN (240).jpg',
'media/DroidconIN (241).jpg',
'media/DroidconIN (242).jpg',
'media/DroidconIN (243).jpg',
'media/DroidconIN (244).jpg',
'media/DroidconIN (245).jpg',
'media/DroidconIN (246).jpg',
'media/DroidconIN (247).jpg',
'media/DroidconIN (248).jpg',
'media/DroidconIN (249).jpg',
'media/DroidconIN (250).jpg',
'media/DroidconIN (251).jpg',
'media/DroidconIN (252).jpg',
'media/DroidconIN (253).jpg',
'media/DroidconIN (254).jpg',
'media/DroidconIN (255).jpg',
'media/DroidconIN (256).jpg',
'media/DroidconIN (257).jpg',
'media/DroidconIN (258).jpg',
'media/DroidconIN (259).jpg',
'media/DroidconIN (260).jpg',
'media/DroidconIN (261).jpg',
'media/DroidconIN (262).jpg',
'media/DroidconIN (263).jpg',
'media/DroidconIN (264).jpg',
'media/DroidconIN (265).jpg',
'media/DroidconIN (266).jpg',
'media/DroidconIN (267).jpg',
'media/DroidconIN (268).jpg',
'media/DroidconIN (269).jpg',
'media/DroidconIN (270).jpg',
'media/DroidconIN (271).jpg',
'media/DroidconIN (272).jpg',
'media/DroidconIN (273).jpg',
'media/DroidconIN (274).jpg',
'media/DroidconIN (275).jpg',
'media/DroidconIN (276).jpg',
'media/DroidconIN (277).jpg',
'media/DroidconIN (278).jpg',
'media/DroidconIN (279).jpg',
'media/DroidconIN (280).jpg',
'media/DroidconIN (281).jpg',
'media/DroidconIN (282).jpg',
'media/DroidconIN (283).jpg',
'media/DroidconIN (284).jpg',
'media/DroidconIN (285).jpg',
'media/DroidconIN (286).jpg',
'media/DroidconIN (287).jpg',
'media/DroidconIN (288).jpg',
'media/DroidconIN (289).jpg',
'media/DroidconIN (290).jpg',
'media/DroidconIN (291).jpg',
'media/DroidconIN (292).jpg',
'media/DroidconIN (293).jpg',
'media/DroidconIN (294).jpg',
'media/DroidconIN (295).jpg',
'media/DroidconIN (296).jpg',
'media/DroidconIN (297).jpg',
'media/DroidconIN (298).jpg',
'media/DroidconIN (299).jpg',
'media/DroidconIN (300).jpg',
'media/DroidconIN (301).jpg',
'media/DroidconIN (302).jpg',
'media/DroidconIN (303).jpg',
'media/DroidconIN (304).jpg',
'media/DroidconIN (305).jpg',
'media/DroidconIN (306).jpg',
'media/DroidconIN (307).jpg',
'media/DroidconIN (308).jpg',
'media/DroidconIN (309).jpg',
'media/DroidconIN (310).jpg',
'media/DroidconIN (311).jpg',
'media/DroidconIN (312).jpg',
'media/DroidconIN (313).jpg',
'media/DroidconIN (314).jpg',
'media/DroidconIN (315).jpg',
'media/DroidconIN (316).jpg',
'media/DroidconIN (317).jpg',
'media/DroidconIN (318).jpg',
'media/DroidconIN (319).jpg',
'media/DroidconIN (320).jpg',
'media/DroidconIN (321).jpg',
'media/DroidconIN (322).jpg',
'media/DroidconIN (323).jpg',
'media/DroidconIN (324).jpg',
'media/DroidconIN (325).jpg',
'media/DroidconIN (326).jpg',
'media/DroidconIN (327).jpg',
'media/DroidconIN (328).jpg',
'media/DroidconIN (329).jpg',
'media/DroidconIN (330).jpg',
'media/DroidconIN (331).jpg',
'media/DroidconIN (332).jpg',
'media/DroidconIN (333).jpg',
'media/DroidconIN (334).jpg',
'media/DroidconIN (335).jpg',
'media/DroidconIN (336).jpg',
'media/DroidconIN (337).jpg',
'media/DroidconIN (338).jpg',
'media/DroidconIN (339).jpg',
'media/DroidconIN (340).jpg',
'media/DroidconIN (341).jpg',
'media/DroidconIN (342).jpg',
'media/DroidconIN (343).jpg',
'media/DroidconIN (344).jpg',
// 'media/DroidconIN (345).jpg',
'media/DroidconIN (346).jpg',
'media/DroidconIN (347).jpg',
'media/DroidconIN (348).jpg',
'media/DroidconIN (349).jpg',
'media/DroidconIN (350).jpg',
'media/DroidconIN (351).jpg',
'media/DroidconIN (352).jpg',
'media/DroidconIN (353).jpg',
'media/DroidconIN (354).jpg',
'media/DroidconIN (355).jpg',
'media/DroidconIN (356).jpg',
'media/DroidconIN (357).jpg',
'media/DroidconIN (358).jpg',
'media/DroidconIN (359).jpg',
'media/DroidconIN (360).jpg',
'media/DroidconIN (361).jpg',
'media/DroidconIN (362).jpg',
'media/DroidconIN (363).jpg',
'media/DroidconIN (364).jpg',
'media/DroidconIN (365).jpg',
'media/DroidconIN (366).jpg',
'media/DroidconIN (367).jpg',
'media/DroidconIN (368).jpg',
'media/DroidconIN (369).jpg',
'media/DroidconIN (370).jpg',
'media/DroidconIN (371).jpg',
'media/DroidconIN (372).jpg',
'media/DroidconIN (373).jpg',
'media/DroidconIN (374).jpg',
'media/DroidconIN (375).jpg',
'media/DroidconIN (376).jpg',
'media/DroidconIN (377).jpg',
'media/DroidconIN (378).jpg',
'media/DroidconIN (379).jpg',
'media/DroidconIN (380).jpg',
'media/DroidconIN (381).jpg',
'media/DroidconIN (382).jpg',
'media/DroidconIN (383).jpg',
'media/DroidconIN (384).jpg',
'media/DroidconIN (385).jpg',
'media/DroidconIN (386).jpg',
'media/DroidconIN (387).jpg',
'media/DroidconIN (388).jpg',
'media/DroidconIN (389).jpg',
'media/DroidconIN (390).jpg',
'media/DroidconIN (391).jpg',
'media/DroidconIN (392).jpg',
'media/DroidconIN (393).jpg',
'media/DroidconIN (394).jpg',
'media/DroidconIN (395).jpg',
'media/DroidconIN (396).jpg',
'media/DroidconIN (397).jpg',
'media/DroidconIN (398).jpg',
'media/DroidconIN (399).jpg',
'media/DroidconIN (400).jpg',
'media/DroidconIN (401).jpg',
'media/DroidconIN (402).jpg',
'media/DroidconIN (403).jpg',
'media/DroidconIN (404).jpg',
'media/DroidconIN (405).jpg',
'media/DroidconIN (406).jpg',
'media/DroidconIN (407).jpg',
'media/DroidconIN (408).jpg',
'media/DroidconIN (409).jpg',
'media/DroidconIN (410).jpg',
'media/DroidconIN (411).jpg',
'media/DroidconIN (412).jpg',
'media/DroidconIN (413).jpg',
'media/DroidconIN (414).jpg',
'media/DroidconIN (415).jpg',
'media/DroidconIN (416).jpg',
'media/DroidconIN (417).jpg',
'media/DroidconIN (418).jpg',
'media/DroidconIN (419).jpg',
'media/DroidconIN (420).jpg',
'media/DroidconIN (421).jpg',
'media/DroidconIN (422).jpg',
'media/DroidconIN (423).jpg',
'media/DroidconIN (424).jpg',
'media/DroidconIN (425).jpg',
'media/DroidconIN (426).jpg',
'media/DroidconIN (427).jpg',
'media/DroidconIN (428).jpg',
'media/DroidconIN (429).jpg',
'media/DroidconIN (430).jpg',
'media/DroidconIN (431).jpg',
'media/DroidconIN (432).jpg',
'media/DroidconIN (433).jpg',
'media/DroidconIN (434).jpg',
'media/DroidconIN (435).jpg',
'media/DroidconIN (436).jpg',
'media/DroidconIN (437).jpg',
'media/DroidconIN (438).jpg',
'media/DroidconIN (439).jpg',
'media/DroidconIN (440).jpg',
'media/DroidconIN (441).jpg',
'media/DroidconIN (442).jpg',
'media/DroidconIN (443).jpg',
'media/DroidconIN (444).jpg',
'media/DroidconIN (445).jpg',
'media/DroidconIN (446).jpg',
'media/DroidconIN (447).jpg',
'media/DroidconIN (448).jpg',
'media/DroidconIN (449).jpg',
'media/DroidconIN (450).jpg',
'media/DroidconIN (451).jpg',
'media/DroidconIN (452).jpg',
'media/DroidconIN (453).jpg'];

$(main)
