def gentable(data):
    colsizes = [2, 4, 3, 3]
    print '<ul class="grid schedule container-fluid">'
    headers = data[:2]
    for row in headers:
        print '  <li class="row-fluid header">'
        for counter, col in enumerate(row):
            print (u'    <div class="span%d">%s</div>' % (colsizes[counter], col or '&nbsp;')).encode('utf-8')
        print '  </li>'
    for row in data[2:]:
        print '  <li class="row-fluid item">'
        for counter, item in enumerate(row):
            if isinstance(item, dict):
                item['sectionname'] = '-'.join(item.get('section', '').lower().replace('&', '').replace(',', '').split(' '))
                item['levelname'] = '-'.join(item.get('level', '').lower().replace('&', '').replace(',', '').split(' '))
                print '    <div class="span%d">' % colsizes[counter]
                print '    <div class="session-box {sectionname}" title="{section}">'.format(**item)
                if item.get('url'):
                    print '      <a href="{url}" target="_blank">{title}</a><br><div class="author">{speaker}</div><br><div class="{levelname}" title="{level}"></div>'.format(**item)
                else:
                    print '      {title}<br>&mdash;{speaker}'.format(**item)
                print '    </div></div>'
            else:
                print (u'    <div class="span%d">%s</div>' % (colsizes[counter], item)).encode('utf-8')
        print '  </li>'
    print '</ul>'

gentable([
 ['', 'Day 1', '', ''],
 ['Rooms', 'Audi', 'Hall', 'Room'],
 ['9:00-10:00', 'Registration', '', ''],
 ['10:00-11:00', 'TBD', '', ''],
 ['11:00-11:30', 'TBD', '', ''],
 ['11:30-12:00', 'Break', '', ''],
 ['12:00-12:30',
  {u'comments': 0,
   u'confirmed': True,
   u'email': None,
   u'id': 506,
   u'level': u'Beginner',
   u'name': u'506-the-real-incident-of-stealing-a-droid-app-data-in-daytime',
   u'phone': None,
   u'proposer': u'Akash Mahajan',
   u'section': u'General Topics',
   u'speaker': u'Akash Mahajan',
   u'submitted': u'2012-09-03T03:24:31',
   u'title': u'The Real Incident of Stealing a Droid App+Data in daytime',
   u'type': u'Lecture',
   u'url': u'http://funnel.hasgeek.com/droidcon2012/506-the-real-incident-of-stealing-a-droid-app-data-in-daytime',
   u'votes': 19},
  'TBD',
  'TBD'],
 ['12:30-1:00',
  {u'comments': 3,
   u'confirmed': True,
   u'email': None,
   u'id': 523,
   u'level': u'Beginner',
   u'name': u'523-augmented-reality-for-navigation-thru-the-galli',
   u'phone': None,
   u'proposer': u'Anenth Guru',
   u'section': u'App Demos',
   u'speaker': u'Anenth Guru',
   u'submitted': u'2012-09-12T10:56:47',
   u'title': u'Augmented Reality for Navigation - Thru the Galli',
   u'type': u'Demo',
   u'url': u'http://funnel.hasgeek.com/droidcon2012/523-augmented-reality-for-navigation-thru-the-galli',
   u'votes': 16},
  'TBD',
  'TBD'],
 ['1:00-1:30', 'Lunch', '', ''],
 ['1:30-2:00', 'Lunch', '', ''],
 ['2:00-2:30',
  {u'comments': 0,
   u'confirmed': True,
   u'email': None,
   u'id': 548,
   u'level': u'Intermediate',
   u'name': u'548-using-appcelerator-titanium-to-build-native-android-apps-without-the-native-pain',
   u'phone': None,
   u'proposer': u'Gaurav Kheterpal',
   u'section': u'Platforms, Tools & Libraries',
   u'speaker': u'Gaurav Kheterpal',
   u'submitted': u'2012-10-03T11:15:12',
   u'title': u'Using Appcelerator Titanium To Build Native Android Apps Without The Native Pain',
   u'type': u'Workshop',
   u'url': u'http://funnel.hasgeek.com/droidcon2012/548-using-appcelerator-titanium-to-build-native-android-apps-without-the-native-pain',
   u'votes': 11},
  'TBD',
  'TBD'],
 ['2:30-3:00',
  {u'comments': 0,
   u'confirmed': True,
   u'email': None,
   u'id': 499,
   u'level': u'Intermediate',
   u'name': u'499-constructive-design-for-android',
   u'phone': None,
   u'proposer': u'Isaac Wesley',
   u'section': u'Specialized Topics',
   u'speaker': u'Isaac Wesley',
   u'submitted': u'2012-08-31T14:58:10',
   u'title': u'Constructive Design for Android',
   u'type': u'Lecture',
   u'url': u'http://funnel.hasgeek.com/droidcon2012/499-constructive-design-for-android',
   u'votes': 26},
  'TBD',
  'TBD'],
 ['3:00-3:30',
  {u'comments': 4,
   u'confirmed': True,
   u'email': None,
   u'id': 497,
   u'level': u'Intermediate',
   u'name': u'497-microsoft-kinect-and-android',
   u'phone': None,
   u'proposer': u'Allen Thomas Varghese',
   u'section': u'App Demos',
   u'speaker': u'Allen Thomas Varghese',
   u'submitted': u'2012-08-31T14:42:56',
   u'title': u'Microsoft Kinect and Android',
   u'type': u'Demo',
   u'url': u'http://funnel.hasgeek.com/droidcon2012/497-microsoft-kinect-and-android',
   u'votes': 13},
  'TBD',
  'TBD'],
 ['3:30-4:00', 'Break', '', ''],
 ['4:00-4:30',
  {u'comments': 2,
   u'confirmed': True,
   u'email': None,
   u'id': 547,
   u'level': u'Beginner',
   u'name': u'547-move-as-i-speak',
   u'phone': None,
   u'proposer': u'Phanindra Rachamalla',
   u'section': u'Specialized Topics',
   u'speaker': u'Phanindra Rachamalla',
   u'submitted': u'2012-10-01T18:07:19',
   u'title': u'Move as i speak',
   u'type': u'Demo',
   u'url': u'http://funnel.hasgeek.com/droidcon2012/547-move-as-i-speak',
   u'votes': 30},
  'TBD',
  'TBD'],
 ['4:30-5:00',
  {u'comments': 3,
   u'confirmed': True,
   u'email': None,
   u'id': 444,
   u'level': u'Intermediate',
   u'name': u'444-nosql-location-based-queries-on-android-couchdb-mobile-replication-and-lucene',
   u'phone': None,
   u'proposer': u'Sameer Segal',
   u'section': u'Specialized Topics',
   u'speaker': u'Sameer Segal',
   u'submitted': u'2012-08-08T04:58:01',
   u'title': u'NoSQL & Location based queries on Android - CouchDB, Mobile Replication and Lucene',
   u'type': u'Tutorial',
   u'url': u'http://funnel.hasgeek.com/droidcon2012/444-nosql-location-based-queries-on-android-couchdb-mobile-replication-and-lucene',
   u'votes': 21},
  'TBD',
  'TBD']])
